export interface BehaviorClass {
  id: string;
  name: string;
  description: string;
  icon: string;
  enabled: boolean;
  sensitivity: number;
  detections24h: number;
  lastTriggered: string;
}

export const BEHAVIOR_CLASSES: BehaviorClass[] = [
  {
    id: "counter-surfing",
    name: "Counter Surfing",
    description: "Dog paws on kitchen counters or tables",
    icon: "🍽️",
    enabled: true,
    sensitivity: 72,
    detections24h: 14,
    lastTriggered: "2026-07-10T18:42:00Z",
  },
  {
    id: "destructive-chewing",
    name: "Destructive Chewing",
    description: "Chewing furniture, shoes, or household items",
    icon: "🦴",
    enabled: true,
    sensitivity: 85,
    detections24h: 8,
    lastTriggered: "2026-07-10T16:15:00Z",
  },
  {
    id: "resource-guarding",
    name: "Resource Guarding",
    description: "Aggressive posture over food, toys, or beds",
    icon: "🛡️",
    enabled: true,
    sensitivity: 68,
    detections24h: 3,
    lastTriggered: "2026-07-09T21:30:00Z",
  },
  {
    id: "compulsive-licking",
    name: "Compulsive Licking",
    description: "Excessive paw or surface licking patterns",
    icon: "👅",
    enabled: false,
    sensitivity: 55,
    detections24h: 0,
    lastTriggered: "2026-07-08T09:12:00Z",
  },
];

export const CAMERAS = [
  {
    id: "cam-kitchen",
    name: "Kitchen — Reolink RLC-810A",
    protocol: "RTSP",
    url: "rtsp://192.168.1.42:554/h264Preview_01_main",
    status: "streaming" as const,
    fps: 15,
    resolution: "2560×1440",
    onvif: true,
    lastFrame: "2s ago",
    detections: 6,
  },
  {
    id: "cam-living",
    name: "Living Room — Amcrest IP4M-1041",
    protocol: "ONVIF",
    url: "rtsp://192.168.1.43:554/cam/realmonitor?channel=1&subtype=0",
    status: "streaming" as const,
    fps: 12,
    resolution: "1920×1080",
    onvif: true,
    lastFrame: "1s ago",
    detections: 4,
  },
  {
    id: "cam-backyard",
    name: "Backyard — Hikvision DS-2CD2043",
    protocol: "RTSP",
    url: "rtsp://192.168.1.44:554/Streaming/Channels/101",
    status: "streaming" as const,
    fps: 10,
    resolution: "1920×1080",
    onvif: false,
    lastFrame: "3s ago",
    detections: 2,
  },
  {
    id: "cam-hallway",
    name: "Hallway — Tapo C210",
    protocol: "RTSP",
    url: "rtsp://192.168.1.45:554/stream1",
    status: "reconnecting" as const,
    fps: 0,
    resolution: "1920×1080",
    onvif: true,
    lastFrame: "45s ago",
    detections: 0,
  },
];

export const ALERTS = [
  {
    id: "alert-001",
    timestamp: "2026-07-10T18:42:33Z",
    behavior: "Counter Surfing",
    camera: "Kitchen — Reolink RLC-810A",
    confidence: 0.94,
    dog: "Biscuit",
    action: "TTS: 'Off the counter!' + Kitchen plug OFF",
    status: "corrected" as const,
    frigateClip: "clip-kitchen-184233",
  },
  {
    id: "alert-002",
    timestamp: "2026-07-10T16:15:08Z",
    behavior: "Destructive Chewing",
    camera: "Living Room — Amcrest IP4M-1041",
    confidence: 0.89,
    dog: "Biscuit",
    action: "Webhook → HA: play_deterrent_sound",
    status: "corrected" as const,
    frigateClip: "clip-living-161508",
  },
  {
    id: "alert-003",
    timestamp: "2026-07-10T14:22:51Z",
    behavior: "Counter Surfing",
    camera: "Kitchen — Reolink RLC-810A",
    confidence: 0.91,
    dog: "Biscuit",
    action: "MQTT → smart_plug.kitchen_lamp OFF",
    status: "corrected" as const,
    frigateClip: "clip-kitchen-142251",
  },
  {
    id: "alert-004",
    timestamp: "2026-07-09T21:30:17Z",
    behavior: "Resource Guarding",
    camera: "Living Room — Amcrest IP4M-1041",
    confidence: 0.87,
    dog: "Biscuit",
    action: "TTS: 'Leave it' + notification to phone",
    status: "acknowledged" as const,
    frigateClip: "clip-living-213017",
  },
  {
    id: "alert-005",
    timestamp: "2026-07-09T19:05:44Z",
    behavior: "Destructive Chewing",
    camera: "Backyard — Hikvision DS-2CD2043",
    confidence: 0.76,
    dog: "Mochi",
    action: "Webhook → HA: backyard_sprinkler_pulse",
    status: "false_positive" as const,
    frigateClip: "clip-backyard-190544",
  },
  {
    id: "alert-006",
    timestamp: "2026-07-09T11:18:22Z",
    behavior: "Counter Surfing",
    camera: "Kitchen — Reolink RLC-810A",
    confidence: 0.93,
    dog: "Biscuit",
    action: "MQTT → media_player.kitchen OFF",
    status: "corrected" as const,
    frigateClip: "clip-kitchen-111822",
  },
  {
    id: "alert-007",
    timestamp: "2026-07-08T20:45:09Z",
    behavior: "Destructive Chewing",
    camera: "Living Room — Amcrest IP4M-1041",
    confidence: 0.88,
    dog: "Biscuit",
    action: "TTS: 'No chew!' + treat dispenser locked",
    status: "corrected" as const,
    frigateClip: "clip-living-204509",
  },
  {
    id: "alert-008",
    timestamp: "2026-07-08T09:12:55Z",
    behavior: "Compulsive Licking",
    camera: "Living Room — Amcrest IP4M-1041",
    confidence: 0.71,
    dog: "Mochi",
    action: "Notification only — class disabled since",
    status: "acknowledged" as const,
    frigateClip: "clip-living-091255",
  },
];

export const AUTOMATIONS = [
  {
    id: "auto-001",
    name: "Counter Surf → Kitchen Plug Off",
    trigger: "counter-surfing",
    action: "mqtt",
    target: "homeassistant/switch/kitchen_counter_plug/set",
    payload: '{"state":"OFF"}',
    enabled: true,
    lastFired: "2026-07-10T18:42:33Z",
    fireCount: 47,
  },
  {
    id: "auto-002",
    name: "Chewing → Deterrent Sound",
    trigger: "destructive-chewing",
    action: "webhook",
    target: "http://192.168.1.10:8123/api/webhook/pawguard_deterrent",
    payload: '{"sound":"ultrasonic_bark_deterrent","volume":0.7}',
    enabled: true,
    lastFired: "2026-07-10T16:15:08Z",
    fireCount: 23,
  },
  {
    id: "auto-003",
    name: "Guarding → TTS Warning",
    trigger: "resource-guarding",
    action: "mqtt",
    target: "homeassistant/tts/speak",
    payload: '{"entity_id":"media_player.living_room","message":"Leave it, Biscuit"}',
    enabled: true,
    lastFired: "2026-07-09T21:30:17Z",
    fireCount: 8,
  },
  {
    id: "auto-004",
    name: "Any Alert → Frigate Clip Tag",
    trigger: "*",
    action: "mqtt",
    target: "frigate/events",
    payload: '{"type":"pawguard","label":"{{behavior}}","score":{{confidence}}}',
    enabled: true,
    lastFired: "2026-07-10T18:42:33Z",
    fireCount: 156,
  },
  {
    id: "auto-005",
    name: "Backyard Chew → Sprinkler Pulse",
    trigger: "destructive-chewing",
    action: "webhook",
    target: "http://192.168.1.10:8123/api/webhook/pawguard_sprinkler",
    payload: '{"zone":"backyard","duration_sec":3}',
    enabled: false,
    lastFired: "2026-07-09T19:05:44Z",
    fireCount: 5,
  },
];

export const FRIGATE_EVENTS = [
  {
    id: "fe-001",
    timestamp: "2026-07-10T18:42:33Z",
    camera: "kitchen",
    label: "pawguard:counter-surfing",
    score: 0.94,
    clipId: "clip-kitchen-184233",
    duration: "12s",
    tagged: true,
  },
  {
    id: "fe-002",
    timestamp: "2026-07-10T16:15:08Z",
    camera: "living_room",
    label: "pawguard:destructive-chewing",
    score: 0.89,
    clipId: "clip-living-161508",
    duration: "18s",
    tagged: true,
  },
  {
    id: "fe-003",
    timestamp: "2026-07-10T14:22:51Z",
    camera: "kitchen",
    label: "pawguard:counter-surfing",
    score: 0.91,
    clipId: "clip-kitchen-142251",
    duration: "9s",
    tagged: true,
  },
  {
    id: "fe-004",
    timestamp: "2026-07-09T21:30:17Z",
    camera: "living_room",
    label: "pawguard:resource-guarding",
    score: 0.87,
    clipId: "clip-living-213017",
    duration: "22s",
    tagged: true,
  },
  {
    id: "fe-005",
    timestamp: "2026-07-09T19:05:44Z",
    camera: "backyard",
    label: "pawguard:destructive-chewing",
    score: 0.76,
    clipId: "clip-backyard-190544",
    duration: "15s",
    tagged: false,
  },
];

export const MQTT_LOG = [
  { time: "18:42:33", topic: "frigate/events", payload: '{"type":"pawguard","label":"counter-surfing","score":0.94}', direction: "out" as const },
  { time: "18:42:33", topic: "homeassistant/switch/kitchen_counter_plug/set", payload: '{"state":"OFF"}', direction: "out" as const },
  { time: "18:42:32", topic: "pawguard/detections", payload: '{"camera":"kitchen","behavior":"counter-surfing","confidence":0.94}', direction: "out" as const },
  { time: "16:15:08", topic: "frigate/events", payload: '{"type":"pawguard","label":"destructive-chewing","score":0.89}', direction: "out" as const },
  { time: "16:15:08", topic: "pawguard/webhook/fired", payload: '{"url":"pawguard_deterrent","status":200}', direction: "out" as const },
  { time: "16:14:55", topic: "frigate/kitchen/person/snapshot", payload: '[binary 142KB]', direction: "in" as const },
  { time: "14:22:51", topic: "homeassistant/switch/kitchen_counter_plug/set", payload: '{"state":"OFF"}', direction: "out" as const },
  { time: "14:22:50", topic: "pawguard/status", payload: '{"inference_ms":34,"model":"yolov8-paw-v2.1"}', direction: "out" as const },
];

export const CHART_DATA = [
  { day: "Jul 4", counter: 2, chewing: 1, guarding: 0, licking: 0 },
  { day: "Jul 5", counter: 3, chewing: 2, guarding: 1, licking: 0 },
  { day: "Jul 6", counter: 1, chewing: 0, guarding: 0, licking: 1 },
  { day: "Jul 7", counter: 4, chewing: 3, guarding: 0, licking: 0 },
  { day: "Jul 8", counter: 2, chewing: 2, guarding: 1, licking: 2 },
  { day: "Jul 9", counter: 3, chewing: 1, guarding: 1, licking: 0 },
  { day: "Jul 10", counter: 5, chewing: 2, guarding: 0, licking: 0 },
];

export const DOCKER_STATUS = {
  image: "pawguard/pawguard:2.1.0",
  uptime: "14d 6h 22m",
  cpu: 18,
  memory: 1.2,
  memoryMax: 4,
  inferenceMs: 34,
  model: "yolov8-paw-v2.1.onnx",
  license: "PG-PERP-7X4K-9M2N",
  licenseType: "Perpetual",
  expiresAt: null,
};

export const LICENSE_KEYS = [
  { key: "PG-PERP-7X4K-9M2N", type: "Perpetual", customer: "Marcus Chen", email: "marcus@homelab.io", activated: "2026-03-15", status: "active" },
  { key: "PG-SUB-A3B7-C1D2", type: "Annual", customer: "Sarah Whitfield", email: "sarah.w@selfhost.dev", activated: "2026-01-22", status: "active" },
  { key: "PG-SUB-E5F6-G7H8", type: "Annual", customer: "Jake Morrison", email: "jake@frigatefan.com", activated: "2025-11-08", status: "expired" },
];
